version: "2"

formatters:
  enable:
    - gofmt
    - goimports
    - golines

linters:
  enable:
    - copyloopvar
    - err113
    - errorlint
    - exptostd
    - depguard
    - fatcontext
    - gocritic
    - govet
    - iface
    - importas
    - intrange
    - mirror
    - misspell
    - nakedret
    - nlreturn
    - nolintlint
    - perfsprint
    - protogetter
    - sloglint
    - staticcheck
    - tagalign
    - testifylint
    - usestdlibvars
    - usetesting
    - whitespace
    - wsl_v5
  settings:
    depguard:
      rules:
        main:
          allow:
            - $gostd
            - github.com/labset/protoc-gen-sqlc
            - github.com/bufbuild/protocompile
            - github.com/stretchr/testify
            - google.golang.org/protobuf
            - gopkg.in/yaml.v3
